spring.application.name=asistencia

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#esta linea solo va en desarrollo no en produccion
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/asistenciasDB
spring.datasource.username=postgres
spring.datasource.password=Joel2004

##Debemos agregar esta linea para poder saber que hace el postgresql
spring.jpa.show-sql=true