spring.application.name=asistencia

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#esta linea solo va en desarrollo no en produccion
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/asistenciasDB
spring.datasource.username=postgres
spring.datasource.password=Admin..

##Debemos agregar esta linea para poder saber que hace el postgresql
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:opticaAmerica2026ClaveSecretaParaJWTAsistenciaUisrael}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alexander777800@gmail.com
spring.mail.password=fggu becp vuad vgqj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://localhost:8081


